### ISSUE TITLE
zigamma.reg full = TRUE

### ISSUE THREAD

**Issue by jdlabban** [RfastOfficial/Rfast2#17]
Getting this error for zigamma.reg when "full" is set to "TRUE":
Error in `rownames<-`(`*tmp*`, value = colnames(x)) : 
  attempt to set 'rownames' on an object with no dimensions
The error is replicated even when using the example.
Thanks.

**Comment by statlink** [comment]
I think we have fixed this problem. Can you try again now with the newest version?
