### ISSUE TITLE
Can't install on Ubuntu 20.04.4 LTS with R 3.6.3 

### ISSUE THREAD

**Issue by Lenticular** [RfastOfficial/Rfast2#18]
I realise that this is an old version of R on a rather old OS version (although still supported), but as far as I can tell I have all the required package versions (including Rcpp 1.0.3). However, when I try to install from CRAN with:

`install.packages(Rfast2)`

I get the following message: 

`** R
Error in parse(outFile) : 
  /tmp/RtmpfXWq0m/R.INSTALL286524c372d3e/Rfast2/R/onAttach.R:7:26: unexpected string constant
6:         msg <-  paste(
7:                         r"( ___ __ __ __ __    __ __ __ __ __ _              _               __ __ __ __ __     __ __ __ __ __ __   )"
                            ^
ERROR: unable to collate and parse R files for package ‘Rfast2’`

Any idea how I might fix or circumvent this? 
Thanks in advance!

**Comment by ManosPapadakis95** [comment]
I don't think that this is our problem. Perhaps you need to update R (>=3.5).
