### ISSUE TITLE
Error in Rfast2/R/phi_divergence_prop_reg.R:86:52: unexpected '{'

### ISSUE THREAD

**Issue by SamoPP** [RfastOfficial/Rfast2#2]
There is an error in Rfast2/R/phi_divergence_prop_reg.R:86:52: unexpected '{' [(https://github.com/RfastOfficial/Rfast2/blob/master/R/phi_divergence_prop_reg.R)](https://github.com/RfastOfficial/Rfast2/blob/master/R/phi_divergence_prop_reg.R)

There should be a " <- function(..." in line 86 since now the code in line 86 is "prophelling.reg(y, x, tol = 1e-07, maxiters = 100) {" like this "prophelling.reg<-function(y, x, tol = 1e-07, maxiters = 100) {"

**Comment by statlink** [comment]
This is one of the new functions that have not been fully corrected. 
Probably more mistakes will arise, but we are working on them.
