### ISSUE TITLE
Latest Rfast2 update is broken: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?

### ISSUE THREAD

**Issue by barracuda156** [RfastOfficial/Rfast2#23]
Now it fails to build on macOS 13:
```
  using C compiler: ‘clang version 15.0.7’
  using C++ compiler: ‘clang version 15.0.7’
  using C++17
  using SDK: ‘MacOSX13.3.sdk’
  /opt/local/bin/clang++-mp-15 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/Rcpp/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/RcppArmadillo/include' -I'/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/RcppParallel/include' -I/opt/local/include -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk   -fopenmp -fPIC  -pipe -Os -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64  -c Eval.cpp -o Eval.o
  In file included from Eval.cpp:7:
  In file included from ../inst/include/Rfast2/templates.h:10:
  ../inst/include/Rfast2/parallel.h:15:9: warning: 201703L [-W#pragma-messages]
  #pragma message STR(__cplusplus)
          ^
  ../inst/include/Rfast2/parallel.h:19:9: warning: Parallel is supported [-W#pragma-messages]
  #pragma message "Parallel is supported"
          ^
  ../inst/include/Rfast2/parallel.h:43:28: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
              std::sort(std::execution::par, begin, end);
                        ~~~~~^~~~~~~~~
                             exception
  /opt/local/libexec/llvm-15/bin/../include/c++/v1/exception:100:29: note: 'exception' declared here
  class _LIBCPP_EXCEPTION_ABI exception
                              ^
  In file included from Eval.cpp:7:
  In file included from ../inst/include/Rfast2/templates.h:10:
  ../inst/include/Rfast2/parallel.h:43:39: error: no member named 'par' in 'std::exception'
              std::sort(std::execution::par, begin, end);
                        ~~~~~~~~~~~~~~~~^
  ../inst/include/Rfast2/parallel.h:60:35: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
              std::nth_element(std::execution::par, begin, middle, end);
                               ~~~~~^~~~~~~~~
                                    exception
  /opt/local/libexec/llvm-15/bin/../include/c++/v1/exception:100:29: note: 'exception' declared here
  class _LIBCPP_EXCEPTION_ABI exception
                              ^
  In file included from Eval.cpp:7:
  In file included from ../inst/include/Rfast2/templates.h:10:
  ../inst/include/Rfast2/parallel.h:60:46: error: no member named 'par' in 'std::exception'
              std::nth_element(std::execution::par, begin, middle, end);
                               ~~~~~~~~~~~~~~~~^
  ../inst/include/Rfast2/parallel.h:77:35: error: no member named 'execution' in namespace 'std'; did you mean 'exception'?
              std::nth_element(std::execution::par, begin, middle, end, cmp);
                               ~~~~~^~~~~~~~~
                                    exception
  /opt/local/libexec/llvm-15/bin/../include/c++/v1/exception:100:29: note: 'exception' declared here
  class _LIBCPP_EXCEPTION_ABI exception
                              ^
  In file included from Eval.cpp:7:
  In file included from ../inst/include/Rfast2/templates.h:10:
  ../inst/include/Rfast2/parallel.h:77:46: error: no member named 'par' in 'std::exception'
              std::nth_element(std::execution::par, begin, middle, end, cmp);
                               ~~~~~~~~~~~~~~~~^
  2 warnings and 6 errors generated.
  make: *** [Eval.o] Error 1
  ERROR: compilation failed for package ‘Rfast2’
```

**Comment by barracuda156** [comment]
@ManosPapadakis95 Could you please take a look into this?

**Comment by barracuda156** [comment]
Also fails on Linux: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/Rfast2-00install.html

**Comment by ManosPapadakis95** [comment]
I am aware of this error. I have fixed it and wait for the mac builder's confirmation.
Sorry for the inconvenience.

**Comment by barracuda156** [comment]
Got it, thank you. Could you refer to the commit fixing it? I will pick that for a patch in Macports.

**Comment by ManosPapadakis95** [comment]
I haven't committed yet and I left home. As soon as I return I will commit the changes.
Thanks 🙏.

**Comment by ManosPapadakis95** [comment]
> Got it, thank you. Could you refer to the commit fixing it? I will pick that for a patch in Macports.

Choose the ```Dev``` branch. The latest commit is the fix for this. I am still waiting for the mac builder.

**Comment by barracuda156** [comment]
@ManosPapadakis95 On a side note, welcome to maintain your package in Macports! Just ping me if you decide to. Our buildbots test on 10.6 through 13 (unfortunately, no PowerPC as of now on build bots, but everything else is there).

**Comment by ManosPapadakis95** [comment]
Thank you! For now I just want to update Rfast2 with any more moves 🤣.

**Comment by durandg12** [comment]
Hello, any update? I have the same issue.

This is the temporary fix I have found, it uses the remotes package and @ManosPapadakis95 previous answer: `remotes::install_github("RfastOfficial/Rfast2", ref="Dev")`

On a side note, I am suprised that the CRAN maintainers let this issue through, but I don't know about their processes.

**Comment by ManosPapadakis95** [comment]
For now the submissions are closed due to vacation.

**Comment by barracuda156** [comment]
@ManosPapadakis95 The bug may be small as such, but it has broken Clangs builds on macOS (which is the standard compiler presently) and at least some Linuxes. “All other” are BeOS, DragonFlyBSD and AmigaOS? :)

**Comment by ManosPapadakis95** [comment]
In linux you can choose gcc instead which is quite better! Personally, I don't know any person that uses linux with clang. I am sure there are some people out there but they must consider to change to gcc. Again, my opinion.
For macos I don't have a solution. Maybe the guys in clang should make faster updates because they have left quite behind. The execution policy is tremendous addition to C++ and the macos people can't enjoy that perfomance.

**Comment by barracuda156** [comment]
I actually use GCC on macOS, so you do not need to convince me, but Macports base defaults are beyond my control.

**Comment by ManosPapadakis95** [comment]
Hahaha. I wonder those guys what were thinking. Anyway, I am not gonna add naything else in the dev repository. I am gonna release an new master and in 2 weeks from I will upload it to the cran.
