### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by joonlee3** [RfastOfficial/Rfast2#25]
Hi,

   I failed to install Rfast2. It seems to be associated with parallel.h.

> * installing *source* package ‘Rfast2’ ...
> ** package ‘Rfast2’ successfully unpacked and MD5 sums checked
> ** using staged installation
> ** libs
> using C compiler: ‘gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)’
> using C++ compiler: ‘g++ (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)’
> using C++17
> /opt/rh/devtoolset-8/root/usr/bin/g++ -std=gnu++17 -I"/opt/R-shared/4.3.0/lib64/R/include" -DNDEBUG -I../inst/include -I'/cloud-home/I0180769/R/x86_64-pc-linux-gnu-library/4.3.0/Rcpp/include' -I'/cloud-home/I0180769/R/x86_64-pc-linux-gnu-library/4.3.0/RcppArmadillo/include' -I'/opt/R/site_lib/RLib_Common/4.3.0/RcppParallel/include' -I/usr/local/include   -fopenmp -fpic  -g -O2  -c Eval.cpp -o Eval.o
> In file included from ../inst/include/Rfast2/templates.h:10,
>                  from Eval.cpp:7:
> ../inst/include/Rfast2/parallel.h:20:10: fatal error: execution: No such file or directory
>  #include <execution>
>           ^~~~~~~~~~~
> compilation terminated.
> make: *** [Eval.o] Error 1
> ERROR: compilation failed for package ‘Rfast2’
> * removing ‘/cloud-home/I0180769/R/x86_64-pc-linux-gnu-library/4.3.0/Rfast2’
> Warning in install.packages :
>   installation of package ‘Rfast2’ had non-zero exit status

If you have any suggestions, please let me know. Thank you.

Best,
Joon

**Comment by ruizederick** [comment]
Hi,

The compiler your using (g++ version 8.3) doesn't support \<execution\> library, you should use g++ version 9 or higher .

` bash
yum install gcc-toolset-9
export PATH=/opt/rh/gcc-toolset-9/root/bin/:$PATH
`
This should solve the problem.
