### ISSUE TITLE
is.lower.tri() seems to be treating upper triangular matrix as lower triangular

### ISSUE THREAD

**Issue by xiao-zang** [RfastOfficial/Rfast2#3]
is.lower.tri() seems to be treating upper triangular matrix as lower triangular matrix, and is.upper.tri() seems to be treating lower triangular matrix as upper triangular matrix. 

Also, the return type seems to be inconsistent between is.lower.tri and is.upper.tri, one being logical and the other being double.

Example:

> smallmat <- matrix(c(1,1,0,1), nrow = 2, byrow=FALSE)
> smallmat
       [,1] [,2]
[1,]    1    0
[2,]    1    1
> is.lower.tri(smallmat)
[1] 0
> is.upper.tri(smallmat)
[1] TRUE
> smallmat2 <- matrix(c(1,1,0,1), nrow = 2, byrow=TRUE)
> smallmat2
       [,1] [,2]
[1,]    1    1
[2,]    0    1
> is.lower.tri(smallmat2)
[1] 1
> is.upper.tri(smallmat2)
[1] FALSE
> typeof(is.upper.tri(smallmat2))
[1] "logical"
> typeof(is.lower.tri(smallmat2))
[1] "double"

**Comment by statlink** [comment]
Cheers for this xiao-zang. We will have a look.

**Comment by ManosPapadakis95** [comment]
Done.

**Comment by xiao-zang** [comment]
> Done.

@ManosPapadakis95 I know it is a dumb question, but how do I install the updated version of Rfast2? Previously I installed Rfast2 using install.packages("Rfast2"), but the package installed in this way is not updated to reflect the fix yet.

**Comment by ManosPapadakis95** [comment]
You need to download the package from github.

**Comment by xiao-zang** [comment]
I did the following:
1) downloaded Rfast2 from GitHub, uncompressed the zip file and compressed the content into Rfast2.tar.gz using terminal command `tar -czf Rfast2.tar.gz Rfast2-master`
2) installed dependencies RANN and Rfast using `install.packages("RANN")`  and `install.packages("Rfast")`
3) tried to install Rfast2 using `install.packages("~/Downloads/Rfast2.tar.gz", repos = NULL, type = "source")`, but got the following error:

clang: error: unsupported option '-fopenmp'
make: *** [._Eval.o] Error 1
ERROR: compilation failed for package ‘Rfast2’

Maybe I did something wrong. Could you kindly advise the correct way to install Rfast2 from GitHub?

Thanks!
